name: Update README

on:
  push:
    branches:
      - main 

permissions:
  contents: write

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: utils
  
      - name: Install ts + ts-node
        id: ts
        run: npm install ts-node typescript @types/node
        working-directory: utils
  
      - name: Run script
        id: script
        run: npx ts-node index.ts
        working-directory: utils
        if: steps.ts.outcome == 'success'

      - name: Update README.md
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "docs: update readme"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}